
SELECT SUM(PAYMENT.AMOUNT) AS REVENUE,
	FILM.TITLE,
	FILM.RENTAL_DURATION,
	FILM.RELEASE_YEAR,
	FILM.RENTAL_RATE,
	FILM.RATING,
	LANGUAGE.NAME AS LANGUAGE,
	CATEGORY.NAME AS GENRE
FROM PAYMENT
INNER JOIN RENTAL ON PAYMENT.RENTAL_ID = RENTAL.RENTAL_ID
INNER JOIN INVENTORY ON RENTAL.INVENTORY_ID = INVENTORY.INVENTORY_ID
INNER JOIN FILM ON INVENTORY.FILM_ID = FILM.FILM_ID
INNER JOIN FILM_CATEGORY ON FILM.FILM_ID = FILM_CATEGORY.FILM_ID
INNER JOIN CATEGORY ON FILM_CATEGORY.CATEGORY_ID = CATEGORY.CATEGORY_ID
INNER JOIN LANGUAGE ON FILM.LANGUAGE_ID = LANGUAGE.LANGUAGE_ID
GROUP BY FILM.TITLE,
	FILM.RENTAL_DURATION,
	FILM.RELEASE_YEAR,
	FILM.RENTAL_RATE,
	FILM.RATING,
	LANGUAGE,
	GENRE
ORDER BY REVENUE DESC;
